//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Species
    {
        public int ProductId { get; set; }
        public int SpeciesId { get; set; }
    
        public virtual PetProduct PetProduct { get; set; }
        public virtual Species Species { get; set; }
    }
}
